# Render the README / pkgdown figures into man/figures from the shipped data.
# Run from the package root after any change to the plots or the example data:
#   source("data-raw/make_figures.R")
devtools::load_all(".", quiet = TRUE)
dir.create("man/figures", showWarnings = FALSE, recursive = TRUE)
ds <- gc_indices(gc_example)
cu <- gc_indices(gc_cuttings)
sv <- function(p, name, w = 8, h = 5) ggplot2::ggsave(file.path("man/figures", name), p, width = w, height = h, dpi = 110, bg = gc_colours("parchment"))
sv(plot_depth_profile(ds, "SRA", c("TOC", "S2", "Tmax", "HI"), holes = c("H01", "H04", "H09", "H12")), "depth_profile.png", 9, 5)
sv(plot_depth_heatmap(ds, "SRA", "TOC"), "depth_heatmap.png", 8, 4.5)
sv(plot_section(ds, "SRA", "TOC", holes = c("H01", "H02", "H03", "H04")), "section.png", 9, 4.5)
sv(plot_map(ds, "SRA", "TOC", depth = c(50, 110)), "map_toc.png", 7, 6)
sv(plot_map(ds, "XRF", "Mo", depth = c(50, 110), fun = max), "map_mo.png", 7, 6)
sv(plot_ternary(ds, "XRD", c("quartz", "carbonate", "clay"), colour = "depth_mid"), "ternary.png", 6, 5.5)
sv(plot_kerogen(ds, "hi_oi"), "kerogen_hi_oi.png", 6, 5)
sv(plot_kerogen(cu, "hi_tmax", colour = "formation"), "kerogen_hi_tmax.png", 6, 5)
sv(plot_mineralogy(ds, holes = c("H01", "H12")), "mineralogy.png", 8, 5)
sv(plot_depth_profile(ds, "XRF", c("SiO2", "CaO", "Mo", "V"), holes = c("H01", "H12")), "depth_profile_xrf.png", 9, 5)
# the cuttings well
sv(plot_depth_profile(cu, "SRA", c("TOC", "S1", "S2", "Tmax", "HI")), "cuttings_sra.png", 10, 6)
sv(plot_pam(cu), "cuttings_pam.png", 5, 7)
sv(plot_mineralogy(cu), "cuttings_mineralogy.png", 5.5, 7)
sv(plot_depth_profile(cu, "XRF", c("Si", "Ca", "Al", "V", "Mo", "U")), "cuttings_xrf.png", 11, 6)
sv(plot_ternary(cu, "XRD", c("quartz", "carbonate", "clay"), colour = "formation"), "cuttings_ternary.png", 6, 5.5)
for (f in list.files("man/figures", full.names = TRUE)) cat(basename(f), file.size(f) %/% 1024, "KB\n")
